theme: 
  - osuny
  - osuny-plugin-centered-header
  - osuny-plugin-centered-footer
_merge: deep
params:
  breadcrumb:
    position: hero-end
  summary:
    position: hero
  home:
    head:
      title: site
  search:
    active: true
  logo:
    header: '/assets/images/logo-white.svg'
    footer: '/assets/images/icon.svg'
  menu:
    primary:
      level_2:
        summary:
          active: false
          source: "Summary" # "Summary" | "meta_description"
          truncate: 125
        title:
          active: true
          summary:
            active: true
            source: "Summary" # "Summary" | "meta_description"
            truncate: 125
  posts:
    index:
      layout: list # grid | list
      options:
        author: false
        categories: true
        date: true
        image: false
        reading_time: true
        summary: true
        subtitle: true
    single:
      options:
        signature: true